### ISSUE TITLE
how to compile for 32 bit cpu

### ISSUE THREAD

**Issue by intheway** [viruscamp/luadec#39]
This luadec is a greate library! It works fine.
But I have a question.
my mac is 64 bit, so the binary is x86_64.
i can compile lua for i386, but when set the "-arch i386" flag for luadec/Makefile, it still compile faied.
error: Undefined symbols for architecture x86_64:
could you tell me how to compile for 32 bit cpu? Thanks!

**Comment by jeffallen** [comment]
You need to add 32-bit to the link step too:

diff --git a/luadec/Makefile b/luadec/Makefile
index c392f34..9350c6a 100644
--- a/luadec/Makefile
+++ b/luadec/Makefile
@@ -14,8 +14,8 @@ CP= cp -f
 RM= rm -f
 
 CC= gcc
-CFLAGS= -O2 -Wall -DSRCVERSION=\"$(SRCVERSION)\" $(INCS) $(MYCFLAGS)
-LDFLAGS= $(MYLDFLAGS)
+CFLAGS= -m32 -O2 -Wall -DSRCVERSION=\"$(SRCVERSION)\" $(INCS) $(MYCFLAGS)
+LDFLAGS= -m32 $(MYLDFLAGS)
 AR= ar rcu
 RANLIB= ranlib
 LIBS= -lm $(MYLIBS)

**Comment by jeffallen** [comment]
Would also be nice to have docs explaining that if you get "bad header" it may be because you are using a 64-bit binary to try to decode a binary meant for a 32-bit interp. The lua header has sizeof(size_t) in it, which ends up 8 on 64-bit platforms.

The solution is to compile lua/luadec with -m32.

**Comment by intheway** [comment]
It works.! Thank you very much.

**Comment by aspyct** [comment]
I couldn't get it to compile with the `-m32` flag: there was an endless stream of incompatible file formats.

However, I somehow had an executable called `i386` on my ubuntu, which starts a shell pretending to be an i386 arch. And it just compiled normally, in 32bit, without needing any modification on the Makefiles of either lua or luadec.

**Comment by f1shf1sh** [comment]
> I couldn't get it to compile with the `-m32` flag: there was an endless stream of incompatible file formats.
> 
> However, I somehow had an executable called `i386` on my ubuntu, which starts a shell pretending to be an i386 arch. And it just compiled normally, in 32bit, without needing any modification on the Makefiles of either lua or luadec.

I also have the same problem:(，have you solve it now? I think i need compile lua with 32bit，but i don't know how to modify Makefile

**Comment by benwong01f611** [comment]
> I also have the same problem:(，have you solve it now? I think i need compile lua with 32bit，but i don't know how to modify Makefile

@f1shf1sh 
Sorry for replying this closed issue, but I think I built 32-bit luadec on my 64-bit Ubuntu and Windows successfully. These are what I did:

1. Add ``-m32`` to ``CFLAGS`` and ``LDFLAGS`` to ``lua-5.x/src/Makefile`` and ``luadec/Makefile``.
2. On Ubuntu, you have to enable i386 architecture with ``sudo dpkg --add-architecture i386`` and install ``libreadline-dev:i386``.
3. On Windows, you need mingw32 instead of mingw64, remember to keep the ``-m32`` parameter.
4. Make sure you clean all previous outputs with ``make clean``, if you are on Windows the Makefile might not delete the outputs properly.

Hope that helps.
